### ISSUE TITLE
warning: failed to create symbolic link for host-networked pods

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/frakti#108]
When creating a pod with host network, it failed to create symbolic link for logs (warning).

pod config 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    name: pod
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirst
  containers:
  - name: nginx
    image: nginx
```

Kubelet events:

```
df21b37c7a7f3aff14ba2034b76d4896406cf501cc59f80b74b49e032934
  36m		36m		1	kubelet, instance-2	spec.containers{nginx}	Warning		Failed		Failed to start container with id a741df21b37c7a7f3aff14ba2034b76d4896406cf501cc59f80b74b49e032934 with error: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/318a363b-0f73-11e7-9e6c-42010a8c0003/nginx_0.log" to the container log file "" for container "a741df21b37c7a7f3aff14ba2034b76d4896406cf501cc59f80b74b49e032934": symlink  /var/log/pods/318a363b-0f73-11e7-9e6c-42010a8c0003/nginx_0.log: no such file or directory
  36m		36m		1	kubelet, instance-2			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "nginx" with rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/318a363b-0f73-11e7-9e6c-42010a8c0003/nginx_0.log" to the container log file "" for container "a741df21b37c7a7f3aff14ba2034b76d4896406cf501cc59f80b74b49e032934": symlink  /var/log/pods/318a363b-0f73-11e7-9e6c-42010a8c0003/nginx_0.log: no such file or directory: "Start Container Failed"
```
