### ISSUE TITLE
[Question] Frakti with Rook.io , error

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/frakti#151]
On a separate system I've installed Kubernetes with kubeadm 1.6.2 & 1.6.4. On the system with standard Kubernetes (non-frakti) Rook.io installs and runs. The rook operator succeeds and runs. On the system with Kubernetes based on Frakti I noticed that the rook operator fails yielding CrashLoopBackOff and no logs generated. Is there some behavior that prevents this from working. I know that on each node, ceph-common is to be installed. Is this an issue where the hypervisor is isolated and does not have access to such modules?

Thanks
DB

**Comment by DarkBlaez** [comment]
I've resolved this by editing rook-operator.yaml and adding a securityContext of privileged to the container section. Am I correct that in doing so this then has Frakti run with dockerd instead of hyperd?

**Comment by feiskyer** [comment]
@DarkBlaez Yep, priviledged containers are running in docker. For Rook.io problem, will figure out what's wrong.

**Comment by DarkBlaez** [comment]
For Rook.io I was able to get the rook-operator to run by setting a securityContext to privileged: true. Now I'm just trying to solve getting the next step, rook-cluster to run

**Comment by feiskyer** [comment]
rook-operator failed because of OOM, after increasing memory, it could start normally:

```yaml
# cat rook-operator.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - secrets
  - pods
  - services
  - nodes
  - configmaps
  - events
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-operator
subjects:
- kind: ServiceAccount
  name: rook-operator
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rook-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rook-operator
    spec:
      serviceAccountName: rook-operator
      containers:
      - name: rook-operator
        image: quay.io/rook/rookd:master-latest
        resources:
          limits:
            memory: 512Mi
        args: ["operator"]
        env:
        - name: ROOKD_REPO_PREFIX
          value: quay.io/rook
```

But there are more problems, you can't change the memory for pods `mon0, mon1, mon2` provisioned by rook operator. Kubernetes doesn't support this because of many reasons.
