### ISSUE TITLE
kube-proxy does not work for hypervisor runtime but OK for OS container

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#252]
Very easy to re-produce:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: default
    protocol: TCP
    port: 8001
    targetPort: 80
```

```
kubectl get ep
nginx         <none>               3m
```

And if add OSContainer annotation to Pod, it will be back as endpoint

[Update] Only happens for latest hyperd upstream master.
